# Site settings
title: Scottland Donaldson
email: scott.p.donaldson@gmail.com
url: http://scottland.cc # the base hostname & protocol for your site
assets: http://scottdonaldson.net-assets.s3-website-us-east-1.amazonaws.com
twitter_username: scottpdonaldson
github_username:  scottdonaldson

# Build settings
kramdown:
    auto_ids: false

exclude: ['aws.json', 'node_modules', 'package.json', 'Gruntfile.js']

permalink: /:title
